version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install -g @angular/cli@6.9.0
      - npm install
  build:
    commands:
      - ng build --configuration=$BUILD_ENV
  post_build:
    commands:
      - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete

